### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by wenyifromsichuan** [YJHCUI/SwinTransformer-YOLOv5#3]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

![20230403145304](https://user-images.githubusercontent.com/49155720/229437008-4bb9372d-4e9a-479b-8a4c-23bfa985304e.png)
在尝试使用您的model训练时，发现了attn的类型为半精度而v的值为全精度从而导致了RuntimeError: expected scalar type Float but found Halfd的问题。
在搜索了相关问题后，发现
Visit https://github.com/Gumpest/YOLOv5-Multibackbone-Compression/issues/58
有相关的提问有类似的问题
![屏幕截图 2023-04-03 152125](https://user-images.githubusercontent.com/49155720/229439215-5d76e705-5042-48a5-a183-b680e5543f15.png)
但参考了相关的回答
![屏幕截图 2023-04-03 152241](https://user-images.githubusercontent.com/49155720/229439538-e4b13ba5-aba3-42e7-a9bb-9765a7bcd164.png)
并没有能解决这个问题。
不知道您是否遇到过你这个问题，希望您能告诉我该如何处理，感谢

### Environment

-python 3.11
-torch 1.19
-cuda 11.6

### Minimal Reproducible Example

        # @: multiply -> [batch_size*num_windows, num_heads, Mh*Mw, embed_dim_per_head]
        # transpose: -> [batch_size*num_windows, Mh*Mw, num_heads, embed_dim_per_head]
        # reshape: -> [batch_size*num_windows, Mh*Mw, total_embed_dim]
        x = (attn @ v).transpose(1, 2).reshape(B_, N, C)
        x = self.proj(x)
        x = self.proj_drop(x)
        return x

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by YJHCUI** [comment]
您好，仓库在一周前进行了一次更新，我刚刚测试了一下，已经解决了这个问题。可以用新仓库的train和val替换一下原来的试一试。

**Comment by wenyifromsichuan** [comment]
感谢您的帮助，这个问题已经解决了
