### ISSUE TITLE
关于swin_transformer的depths和num_heads疑问

### ISSUE THREAD

**Issue by maomao123-git** [YJHCUI/SwinTransformer-YOLOv5#6]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

博主你好。swin_transformer.py里面为啥没有看到tiny版本的embed_dim=96, depths=[2, 2, 6, 2], num_heads=[3, 6, 12, 24]。特别是depths=[2, 2, 6, 2], num_heads=[3, 6, 12, 24]。博主怎么处理的这里？

**Comment by YJHCUI** [comment]
按照YOLOv5的方式配置模型是在yaml里面的。swin_transformer.py里面的代码不包含具体的模型参数。
参考一下说明里的使用swin-tiny作为backbone的yaml配置示例哈，下面是backbone的部分，你具体提到的参数是作为SwinStage的参数传进来的。
PatchEmbed的两个参数第一个就是embed_dim=96
每个SwinStage的第二个参数就是 depths=[2, 2, 6, 2],
第三个参数就是num_heads=[3, 6, 12, 24]
‘’‘
backbone:
  # [from, number, module, args]
  # input [b, 1, 640, 640]
  [[-1, 1, PatchEmbed, [96, 4]],  # 0 [b, 96, 160, 160]
   [-1, 1, SwinStage, [96, 2, 3, 7]],  # 1 [b, 96, 160, 160]
   [-1, 1, PatchMerging, [192]],    # 2 [b, 192, 80, 80]
   [-1, 1, SwinStage, [192, 2, 6, 7]],  # 3 --F0-- [b, 192, 80, 80]
   [ -1, 1, PatchMerging, [384]],   # 4 [b, 384, 40, 40]
   [ -1, 1, SwinStage, [384, 6, 12, 7]], # 5 --F1-- [b, 384, 40, 40]
   [ -1, 1, PatchMerging, [768]],   # 6 [b, 768, 20, 20]
   [ -1, 1, SwinStage, [768, 2, 24, 7]], # 7 --F2-- [b, 768, 20, 20]
  ]
''’
